# Generated by Django 4.2.24 on 2025-09-28 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Genre_List',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_description', models.TextField(blank=True, null=True)),
                ('age_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_url', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_status', models.CharField(choices=[('Currently Running', 'Currently Running'), ('Coming Soon', 'Coming Soon')], default='Coming Soon', max_length=50)),
            ],
            options={
                'db_table': 'Movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieShowtime',
            fields=[
                ('showtime_id', models.AutoField(primary_key=True, serialize=False)),
                ('showtime_value', models.TimeField()),
            ],
            options={
                'db_table': 'Movie_Showtimes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
            options={
                'db_table': 'Movie_Genres',
                'unique_together': {('movie', 'genre')},
            },
        ),
    ]
