# Generated by Django 5.2.6 on 2025-11-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_profile_verification_code_created_at_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('row_label', models.CharField(max_length=1)),
                ('seat_number', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'seats',
                'ordering': ['row_label', 'seat_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('showing_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'showings',
                'ordering': ['start_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('showroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('showroom_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'showrooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('age_category', models.CharField(choices=[('Child', 'Child'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=10)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'managed': False},
        ),
    ]
