# Generated by Django 5.2.6 on 2025-11-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_booking_seat_showing_showroom_ticket_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promotion',
            table='cinema_promotions',
        ),
    ]
